spring:
  cloud:
    gateway:
      enable: true
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product-service
          uri: lb://mi-shop-product
          predicates:
            - Path=/product-api/**
          filters: #过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉1层路径
        - id: order-service
          uri: lb://mi-shop-order
          predicates:
            - Path=/order-api/**
          filters: #过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉1层路径
        - id: user-service
          order: 1 #路由的优先级,数字越小级别越高
          uri: lb://mi-shop-user
          predicates:
            - Path=/user-api/**
          filters: #过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉1层路径
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

    discovery:
      enabled: true