spring:
  config:
    import:
      - nacos:mi-shop-user-dev.yaml?DEFAULT_GROUP
      - nacos:datasource.yaml?group=DEFAULT_GROUP
      - nacos:mybatis-plus.yaml.yaml?group=DEFAULT_GROUP


  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        namespace:  ed278c7d-d38f-424a-9414-8bca6a53c028
      discovery:
        namespace:  ed278c7d-d38f-424a-9414-8bca6a53c028


mybatis-plus:
  configuration:
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
